FROM maven:3.8-adoptopenjdk-8
WORKDIR /quotation-management
COPY target/quotation-management-0.0.1-SNAPSHOT.jar quotation-management.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar", "quotation-management.jar"]