FROM maven:3.8-adoptopenjdk-8
WORKDIR /quotation-management
COPY . .
RUN mvn clean install -Dmaven.test.skip=true
EXPOSE 8081
ENTRYPOINT ["java","-jar", "target/quotation-management-0.0.1-SNAPSHOT.jar"]